cx-api:
  replicaCount: 0
  volumeClaimTemplates:
    storageSize: "5Gi"
  enabled: false

kafka:
  replicaCount: 0
  resources: {}
  kafkaHeapOptions: "-Xmx512m"
  enabled: false

sql-service:
  replicaCount: 0
  service:
    thrift:
      type: "ClusterIP"

solr:
  image:
    tag: 8.3.1
  updateStrategy:
    type: "RollingUpdate"
  javaMem: "-Xmx8g"
  volumeClaimTemplates:
    storageSize: "100Gi"
  replicaCount: 1
  resources: {}
  zookeeper:
    replicaCount: 1
    resources: {}
    env:
      ZK_HEAP_SIZE: 1G

ml-model-service:
  modelRepository:
    impl: fs
    gcs:
      bucketName:
      baseDirectoryName: dev

fusion-admin:
  readinessProbe:
    initialDelaySeconds: 180

fusion-indexing:
  readinessProbe:
    initialDelaySeconds: 180

query-pipeline:
  javaToolOptions: "-Dlogging.level.com.lucidworks.cloud=INFO"
